# Generated by Django 2.1.4 on 2019-02-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_time', models.DateTimeField(verbose_name='usage_time')),
                ('kWh', models.FloatField(verbose_name='kWh')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='user_id')),
                ('area', models.CharField(choices=[('a1', 'a1'), ('a2', 'a2')], max_length=2, verbose_name='area')),
                ('tariff', models.CharField(choices=[('t1', 't1'), ('t2', 't2'), ('t3', 't3')], max_length=2, verbose_name='tariff')),
            ],
        ),
        migrations.AddField(
            model_name='consumotion',
            name='user_id',
            field=models.ManyToManyField(to='consumption.User'),
        ),
    ]
