# Generated by Django 2.1.4 on 2019-02-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='user_id'),
        ),
    ]
