# Generated by Django 2.1.4 on 2019-02-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0002_auto_20190209_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumotion',
            name='id',
        ),
        migrations.AlterField(
            model_name='consumotion',
            name='usage_time',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='usage_time'),
        ),
    ]
