# Generated by Django 2.1.4 on 2019-02-09 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0003_auto_20190209_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='usage_time')),
                ('kWh', models.FloatField(default=0, verbose_name='kWh')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='consumotion',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Consumotion',
        ),
    ]
