# Generated by Django 2.1.4 on 2019-02-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0004_auto_20190209_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='consumer',
        ),
        migrations.AddField(
            model_name='consumption',
            name='consumer',
            field=models.ManyToManyField(to='consumption.User'),
        ),
    ]
