# Generated by Django 2.1.4 on 2019-02-09 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0005_auto_20190209_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='consumer',
        ),
        migrations.AddField(
            model_name='consumption',
            name='consumer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consumption.User'),
        ),
    ]
