# Generated by Django 2.1.4 on 2019-02-11 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0006_auto_20190209_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='usage_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='usage_time'),
        ),
    ]
