# Generated by Django 2.1.4 on 2019-02-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0007_auto_20190211_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumption',
            old_name='consumer',
            new_name='user',
        ),
    ]
