# Generated by Django 2.1.4 on 2019-02-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0009_auto_20190212_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(choices=[('a1', 'a1'), ('a2', 'a2')], db_index=True, max_length=2, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tariff',
            field=models.CharField(choices=[('t1', 't1'), ('t2', 't2'), ('t3', 't3')], db_index=True, max_length=2, verbose_name='tariff'),
        ),
    ]
